### ISSUE TITLE
Restricted topic creation but everyone can post in the topic (comment)

### ISSUE THREAD

**Issue by aclarkmonks** [chris-kent/Easy-Forums#23]
I am trying to restrict topic creation to only forum moderators by setting edit page restriction to only admin and the easy moderators group.....everyone  can view....

But then no one except those in the forum summary page edit rights (adnin, forum moderator) can post on the individual topic pages....even when I have added the easyforum group to the 'can edit' restriction of the individual topic page. 

Am I doing something wrong or is it not possible to restrict topic creation but allow all forum users to post inside those topics ???

**Comment by chris-kent** [comment]
Hi there.

EasyForums does not seperate the Create and edit capabilities in the topic
pages. For topics it uses built in confluence permissions which do not
distinguish between create and edit.

To do this would mean creating a new set of permissions to create topics
and this could turn into an administrator nightmare. As you would need to
manage a permission list for every topic in every forum. I avoided this as
i believed no one would maintain this.

Are you evaluating this ad on?  And how important is this feature?

Cheers
Chris

**Comment by aclarkmonks** [comment]
Hi Chris,

Actually we have a 250 person license ( SEN-9020498) and are using this add-on to manage a Forum / advisory space with our customers.....rather than ending up with customers starting unlimited discussion threads we are trying to be more focused. When we the company or the customer have technical issues or service problems that we believe can or are effecting all of the eco system we submit the item to be raised as a topic to the forum. The forum 'board' members (made up of representatives from our biggest customers and partners) then decide that yes this is an item to enter the forum discussion space......

Once we create the topic....ALL forum members can then comment on the opened topic...

For us this is a very important feature.....as we are looking to try to use this like an advisory board to improve our products and services....but have the ability to be more focused so that it is not specific customer items but only items that have been agreed by all are truely effecting all are discussed in the forum space. this would reduce the amount and number of moderators that we need for the activities....

We really like your Add-in but this is a feature we really do need moving forwards for us.

I also really appreciate the very quick response !

Very best regards

Andrew


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by chris-kent** [comment]
Hi Andrew

This is possible. I see this working as follows.

Currently each Forum can have a distinct set of Moderators. I can add
another option to each forum to specify who can create topics.

This will be either
1. Current behaviour, use the forum page permissions, or
2. Specify a Confluence User Group and only members of this group can
create topics.

The process to set this up will be:
1. Create a user group
2. Add users to group who you want to have permission to create topics
3. Go to the Forum page and any moderator will be able to configure a new
option to only use group in step 1 to create topics.
4. Repeat steps 1 to 3 as needed for other Forums.

If this will meet your requirements then i can do it and have it within a
week.

Please let me know

Cheers
Chris

On 19 Oct 2017 7:32 PM, "aclarkmonks" <notifications@github.com> wrote:

Hi Chris,

Actually we have a 250 person license ( SEN-9020498) and are using this
add-on to manage a Forum / advisory space with our customers.....rather
than ending up with customers starting unlimited discussion threads we are
trying to be more focused. When we the company or the customer have
technical issues or service problems that we believe can or are effecting
all of the eco system we submit the item to be raised as a topic to the
forum. The forum 'board' members (made up of representatives from our
biggest customers and partners) then decide that yes this is an item to
enter the forum discussion space......

Once we create the topic....ALL forum members can then comment on the
opened topic...

For us this is a very important feature.....as we are looking to try to use
this like an advisory board to improve our products and services....but
have the ability to be more focused so that it is not specific customer
items but only items that have been agreed by all are truely effecting all
are discussed in the forum space. this would reduce the amount and number
of moderators that we need for the activities....

We really like your Add-in but this is a feature we really do need moving
forwards for us.

I also really appreciate the very quick response !

Very best regards

Andrew


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by aclarkmonks** [comment]
Hi Chris,

Many thanks and yes, I believe that this would meet our requirements perfectly.

Greatly appreciate the prompt support !

Very best regards

Andrew


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by chris-kent** [comment]
This feature has been added to version 3.9.

One catch however, even if you put a user into a group to Create Topics, they still need Permissions in Confluence to Create content in the Space, so ultimately the users in the group must be a subset of the users who have space permissions to edit/create.

NOTE: I also have allowed Forum Moderators and Admins to always have the capability to create topics. 

I hope that makes sense.

Cheers
Chris
