### ISSUE TITLE
Cannot move EasyForum topics

### ISSUE THREAD

**Issue by JoeAtGitHub** [chris-kent/Easy-Forums#30]
Hi,
when I move Easy Forum pages from one space to another all comments are lost. This results in all topics being unanswered.
Is there a workaround for this behavior?
// Joe

**Comment by chris-kent** [comment]
Hi Joe,

Unfortunately I haven't had a use case for this scenario before, so I don't
have a work-around. I assume this is a Confluence issue not copying the
comments, or maybe it is an option that needs to be turned on to also move
comments when moving the page.??

I found this topic on the issue, and it may be because of permissions in
the Space you are copying too.  As Comments should remain with the page...
https://community.atlassian.com/t5/Confluence-questions/can-t-move-comments-with-pages-in-Confluence/qaq-p/164554

Cheers
Chris

**Comment by chris-kent** [comment]
Hi,
I will close this ticket assuming that the above helped your cause.
Cheers

**Comment by JoeAtGitHub** [comment]
Hi Chris,sorry, I'm still on a long business trip and could not yet test your solution. But it's okay to close the ticket, I will open a new one if necessary.Regards,Joechris-kent <notifications@github.com> hat am 13. Juni 2018 um 14:06 geschrieben:  Hi, I will close this ticket assuming that the above helped your cause. Cheers—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
